### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by corywright** [Parbhat/pelican-blue#6]
The following icons are not present:
- `github-s.png`
- `google.png`
- `mail.png`
- `rss-s.png`

The missing Google+ image results in a broken image as seen in the attached screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/130219/14505362/d46ef67e-0186-11e6-9aef-ce82260a89c6.png).

**Comment by Parbhat** [comment]
@corywright thanks for reporting the issue. The images with **-s** at the end denote the share icons for the articles (shown at the end of the article). For sharing article, github and rss are not required. The images without **-s** are for the sidebar. The theme currently has no google icon for the sidebar. I will add the google icon.
