### ISSUE TITLE
Sidebar does not adapt on small height screens

### ISSUE THREAD

**Issue by JBosm** [Parbhat/pelican-blue#9]
On screens that are wider than high, when screen height is too small, the bottom of the blue column (sidebar/aside) cannot be accessed.
This becomes a limitation when using several pages and/or a long name/description.

**Comment by Parbhat** [comment]
@JBosm thanks for raising the issue. Is there any real device that comes with these dimensions?

**Comment by JBosm** [comment]
Yes, my laptop. I was trying my site with pelican-blue, with 6 pages and one social media. The social was out of screen. I agree that most blogs will not use that many pages.

**Comment by Parbhat** [comment]
@JBosm Yes, adding too many pages in sidebar is rare. You can fork and add a scroll bar to the `sidebar`.

**Comment by Jaxom99** [comment]
it's also the case when you have many tags listed. I will mook into how to add sa croll bar, maybe I can PR here afterwards ?
